# Generated by Django 2.0.7 on 2018-07-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_comment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='data',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='body',
            field=models.TextField(max_length=200),
        ),
    ]
