# Generated by Django 2.0.7 on 2018-07-12 09:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_auto_20180711_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Awards',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='DVD',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ImdbID',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ImdbRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ImdbVotes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Metascore',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Movie_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Ratings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Writer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='boxOffice',
        ),
        migrations.AddField(
            model_name='movie',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
