# Generated by Django 2.0.7 on 2018-07-12 10:56

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_auto_20180712_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
